FROM java:openjdk-8-jdk
# Oppgave 7a, filen kan brukes som den er.
CMD ["touch", "/innicontainer/touchet_fil.txt"]
# Oppgave 7b, kommenter inn disse linjene:
# ADD docker-client-1.0-SNAPSHOT.jar client.jar
# ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/client.jar"]